### ISSUE TITLE
Shadow detection

### ISSUE THREAD

**Issue by saurabhbansal90** [MichiMaestre/Lane-Detection-for-Autonomous-Cars#1]
Hello Miguel, my application is a slow vehicle and there will be lots of strong shadows.
Can you please let me know if you have performed any test with such kind of data.

Saurabh

**Comment by MichiMaestre** [comment]
Hi Saurabh, 

This implementation itself won't perform well in shadows cause I am working with RGB directly. To make it work following this same pipeline you should add an extra step before the edge detection: Convert the image to HSV color space and segment it based on hue values.

**Comment by saurabhbansal90** [comment]
Hello Miguel, thanks for the information.
One more question, whether this code is being used in
